[target.armv7-unknown-linux-gnueabihf]
rustflags = [
    "-C", "target-cpu=cortex-a7",
    "-C", "target-feature=+neon,+vfp4",
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=cortex-a53",
]

[unstable]
build-std = ["std"]
